import { createSlice } from '@reduxjs/toolkit'

// Define the initial state of the authentication slice
const initialState = {
  mode: 'light', // Light or dark mode for UI
  user: null, // User object for the logged-in user
  token: null, // Authentication token
  posts: [], // Array of posts
}

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    // Toggle between light and dark mode
    setMode: (state) => {
      state.mode = state.mode === 'light' ? 'dark' : 'light'
    },
    // Set user and token upon login
    setLogin: (state, action) => {
      state.user = action.payload.user
      state.token = action.payload.token
    },
    // Clear user and token upon logout
    setLogout: (state) => {
      state.user = null
      state.token = null
    },
    // Set or update the user's friends list
    setFriends: (state, action) => {
      if (state.user) {
        state.user.friends = action.payload.friends
      } else {
        console.log('No friends') // Log when there is no user logged in
      }
    },
    // Set or update the list of posts
    setPosts: (state, action) => {
      state.posts = action.payload.posts
    },
    // Update a specific post in the list
    setPost: (state, action) => {
      const updatedPosts = state.posts.map((post) => {
        if (post._id === action.payload.post_id) {
          return action.payload.post
        }
        return post
      })
      state.posts = updatedPosts
    },
  },
})

// Export the actions generated by createSlice
export const { setMode, setLogin, setLogout, setFriends, setPosts, setPost } =
  authSlice.actions

// Export the reducer
export default authSlice.reducer
